@base_url = http://localhost:8080

@token_customer = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTE4MTE2OTUsImlzc3VlciI6InNlY3JldCIsInVzZXJfaWQiOjIzfQ.GvTJ1JcXsrPdy5ERFrdyobV9lU-47GNIFQeac6Kuvu4
@token_super_admin = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjQ5OTU3NjIxNjQsImlzc3VlciI6ImkzWEh2T2JIT3JVVnRmNUluYTgycTJkcmlKYmFDdTcyaXRpRlA4ZE9BeG5wbWJ4aGdoZ3V5IiwidXNlcl9pZCI6MX0.sMs3jS4fz-wjikSmXeP6gXITg557W1a2iM3BtlkXSj4


### Profile
GET {{base_url}}/api/v1/user/profile
Accept: application/json
Content-Type: application/json
Authorization: {{token_super_admin}}

### Change Password
PATCH  {{base_url}}/api/v1/user/change-password
Accept: application/json
Content-Type: application/json
Authorization: {{token_customer}}

{
    "current_password": "talif12345",
    "password_new": "talif123",
    "password_confirmation": "talif123"
}