@baseUrl = http://localhost:8082/api/v1/admin/categories
@accessTokenSuperAdmin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjUzNTM0NTg4MTIsImlzc3VlciI6ImkzWEh2T2JIT3JVVnRmNUluYTgycTJkcmlKYmFDdTcyaXRpRlA4ZE9BeG5wbWJ4aGdoZ3V5IiwidXNlcl9pZCI6OX0.qExsIrS7AAP8wggBPu5dsOobVUFNaAXTKcswD4XNeFg

@accessTokenCustomer = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjUzNTM0NTg5MzksImlzc3VlciI6ImkzWEh2T2JIT3JVVnRmNUluYTgycTJkcmlKYmFDdTcyaXRpRlA4ZE9BeG5wbWJ4aGdoZ3V5IiwidXNlcl9pZCI6MjN9._lmcDQyy2Os6ztmp0-cvhhRIs7qdJQAFl-kVqGyB_F4

### Get all categories
GET {{baseUrl}}?search=&orderBy=&orderType=desc&page=2&perPage=1
Accept: application/json
Authorization: Bearer {{accessTokenSuperAdmin}}


### Get category by ID
GET {{baseUrl}}/6278f670-6806-416a-b216-70692d2336e0
Accept: application/json
Authorization: Bearer {{accessTokenSuperAdmin}}


### Delete category by ID
DELETE {{baseUrl}}/6278f670-6806-416a-b216-70692d2336e0
Accept: application/json
Authorization: Bearer {{accessTokenSuperAdmin}}


### Create new category
POST {{baseUrl}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessTokenSuperAdmin}}

{
    "name": "Solah test",
    "parent_id": "3c2d0f25-38c4-42d1-8f60-d1dcf1c28ae2",
    "icon": "solah",
    "status": "Published",
    "description": "test"
}

### Update new category
PATCH {{baseUrl}}/6278f670-6806-416a-b216-70692d2336e0
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessTokenSuperAdmin}}

{
    "icon": "Adik kecil",
    "name": "test"
}

### Get category by slug
GET {{baseUrl}}/luffy-garp/slug
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessTokenSuperAdmin}}