### login
POST http://localhost:8080/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
    "email": "abdultalif5@gmail.com",
    "password": "talif12345"
}

### Forgot Password
POST http://localhost:8080/api/v1/auth/forgot-password
Accept: application/json
Content-Type: application/json

{
    "email": "abdultalif5@gmail.com"
}


@token_reset = 650d7911-20b8-4cd4-9bcd-1e16ae255313

### Verification Token Reset Password
GET  http://localhost:8080/api/v1/auth/validate-forgot-token?token={{token_reset}}
Accept: application/json
Content-Type: application/json

### Reset Password
PATCH  http://localhost:8080/api/v1/auth/reset-password?token={{token_reset}}
Accept: application/json
Content-Type: application/json

{
    "password_new": "talif12345",
    "password_confirmation": "talif12345"

}

### Register
POST http://localhost:8080/api/v1/auth
Accept: application/json
Content-Type: application/json

{
    "email": "abdultalif55@gmail.com",
    "password": "admin123",
    "name": "Abdul Talif P",
    "confirm_password": "admin123"
}

### Varify Account User
GET http://localhost:8080/api/v1/auth/verify-account?token=c32fc52b-eaa-4c5e-a5ef-c9b6d4a63b19
Accept: application/json
Content-Type: application/json



@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTE2MTc1MTIsImlzc3VlciI6InNlY3JldCIsInVzZXJfaWQiOjIxfQ.7rh8xzyIXBkto7VSgTYyDvC30vPaKMBuQNH2ecsh3cw

### Profile
GET http://localhost:8080/api/v1/profile
Accept: application/json
Content-Type: application/json
Authorization: {{token}}

### Change Password
PATCH  http://localhost:8080/api/v1/change-password
Accept: application/json
Content-Type: application/json
Authorization: {{token}}

{
    "current_password": "talif414",
    "password_new": "talif123",
    "password_confirmation": "talif123"

}