@base_url = http://localhost:8080

@token_customer = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTE4MTE2OTUsImlzc3VlciI6InNlY3JldCIsInVzZXJfaWQiOjIzfQ.GvTJ1JcXsrPdy5ERFrdyobV9lU-47GNIFQeac6Kuvu4
@token_super_admin = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTIxMjc0MjQsImlzc3VlciI6InNlY3JldCIsInVzZXJfaWQiOjl9.4PZqSojYMyXtVNRULyffcFX5nb2D2S3f3sWq1M6NoEU


### Create Role
POST {{base_url}}/api/v1/admin/role
Accept: application/json
Content-Type: application/json
Authorization: {{token_super_admin}}

{
    "name": "Customer"
}

### Delete Role
DELETE {{base_url}}/api/v1/admin/role/7
Accept: application/json
Content-Type: application/json
Authorization: {{token_super_admin}}

### Get Role By ID
GET {{base_url}}/api/v1/admin/role/9
Accept: application/json
Content-Type: application/json
Authorization: {{token_super_admin}}

### Get All Role
GET {{base_url}}/api/v1/admin/role?search=
Accept: application/json
Content-Type: application/json
Authorization: {{token_super_admin}}

### Update Role
PATCH {{base_url}}/api/v1/admin/role/7
Accept: application/json
Content-Type: application/json
Authorization: {{token_super_admin}}

{
    "name": "Talif1213"
}
